DROP FUNCTION IF EXISTS func_getAge;

DELIMITER |

CREATE  FUNCTION `func_getAge`( dob DATE ) RETURNS INT
READS SQL DATA
DETERMINISTIC
BEGIN
    RETURN CEIL(DATEDIFF (NOW(), dob)/365);
END|

DELIMITER ;